global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 2m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'db'
    scrape_interval: 20s
    static_configs:
      - targets: ['db-metrics:9187']
  - job_name: 'docker'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'host.docker.internal:9323' ]
  - job_name: 'traefik'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'traefik:8082' ]
  - job_name: 'blocky-dns'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'blocky-dns:8082' ]

#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'