// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: s-rpc-vault/def.proto

package s_rpc_vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_s_rpc_vault_def_proto protoreflect.FileDescriptor

const file_s_rpc_vault_def_proto_rawDesc = "" +
	"\n" +
	"\x15s-rpc-vault/def.proto\x12\vs_rpc_vault\x1a\x1bgoogle/protobuf/empty.proto2H\n" +
	"\bVaultApi\x12<\n" +
	"\bSnapshot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B;Z9github.com/Cottand/selfosted/dev-go/lib/proto/s-rpc-vaultb\x06proto3"

var file_s_rpc_vault_def_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_s_rpc_vault_def_proto_depIdxs = []int32{
	0, // 0: s_rpc_vault.VaultApi.Snapshot:input_type -> google.protobuf.Empty
	0, // 1: s_rpc_vault.VaultApi.Snapshot:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_rpc_vault_def_proto_init() }
func file_s_rpc_vault_def_proto_init() {
	if File_s_rpc_vault_def_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s_rpc_vault_def_proto_rawDesc), len(file_s_rpc_vault_def_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_rpc_vault_def_proto_goTypes,
		DependencyIndexes: file_s_rpc_vault_def_proto_depIdxs,
	}.Build()
	File_s_rpc_vault_def_proto = out.File
	file_s_rpc_vault_def_proto_goTypes = nil
	file_s_rpc_vault_def_proto_depIdxs = nil
}
