// Code generated by protocplugin. DO NOT EDIT.

package s_rpc_flights

import (
	context "context"
	bedrock "github.com/cottand/selfhosted/dev-go/lib/bedrock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sync "sync"
)

var loadClient = sync.OnceValues(func() (FlightsClient, error) {
	conn, err := bedrock.NewGrpcConn()
	if err != nil {
		return nil, err
	}
	return NewFlightsClient(conn), nil
})

func ListAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flight], error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.ListAll(ctx, in, opts...)
}

func EmissionsForJourney(ctx context.Context, in *Journey, opts ...grpc.CallOption) (*EmissionsForJourneyResponse, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.EmissionsForJourney(ctx, in, opts...)
}
