// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: s-rpc-flights/def.proto

package s_rpc_flights

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flights_ListAll_FullMethodName             = "/s_rpc_flights.Flights/ListAll"
	Flights_EmissionsForJourney_FullMethodName = "/s_rpc_flights.Flights/EmissionsForJourney"
)

// FlightsClient is the client API for Flights service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightsClient interface {
	ListAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flight], error)
	EmissionsForJourney(ctx context.Context, in *Journey, opts ...grpc.CallOption) (*EmissionsForJourneyResponse, error)
}

type flightsClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightsClient(cc grpc.ClientConnInterface) FlightsClient {
	return &flightsClient{cc}
}

func (c *flightsClient) ListAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flight], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Flights_ServiceDesc.Streams[0], Flights_ListAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Flight]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Flights_ListAllClient = grpc.ServerStreamingClient[Flight]

func (c *flightsClient) EmissionsForJourney(ctx context.Context, in *Journey, opts ...grpc.CallOption) (*EmissionsForJourneyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmissionsForJourneyResponse)
	err := c.cc.Invoke(ctx, Flights_EmissionsForJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightsServer is the server API for Flights service.
// All implementations must embed UnimplementedFlightsServer
// for forward compatibility.
type FlightsServer interface {
	ListAll(*emptypb.Empty, grpc.ServerStreamingServer[Flight]) error
	EmissionsForJourney(context.Context, *Journey) (*EmissionsForJourneyResponse, error)
	mustEmbedUnimplementedFlightsServer()
}

// UnimplementedFlightsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightsServer struct{}

func (UnimplementedFlightsServer) ListAll(*emptypb.Empty, grpc.ServerStreamingServer[Flight]) error {
	return status.Error(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedFlightsServer) EmissionsForJourney(context.Context, *Journey) (*EmissionsForJourneyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmissionsForJourney not implemented")
}
func (UnimplementedFlightsServer) mustEmbedUnimplementedFlightsServer() {}
func (UnimplementedFlightsServer) testEmbeddedByValue()                 {}

// UnsafeFlightsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightsServer will
// result in compilation errors.
type UnsafeFlightsServer interface {
	mustEmbedUnimplementedFlightsServer()
}

func RegisterFlightsServer(s grpc.ServiceRegistrar, srv FlightsServer) {
	// If the following call panics, it indicates UnimplementedFlightsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flights_ServiceDesc, srv)
}

func _Flights_ListAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlightsServer).ListAll(m, &grpc.GenericServerStream[emptypb.Empty, Flight]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Flights_ListAllServer = grpc.ServerStreamingServer[Flight]

func _Flights_EmissionsForJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Journey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightsServer).EmissionsForJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flights_EmissionsForJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightsServer).EmissionsForJourney(ctx, req.(*Journey))
	}
	return interceptor(ctx, in, info, handler)
}

// Flights_ServiceDesc is the grpc.ServiceDesc for Flights service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flights_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s_rpc_flights.Flights",
	HandlerType: (*FlightsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmissionsForJourney",
			Handler:    _Flights_EmissionsForJourney_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAll",
			Handler:       _Flights_ListAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "s-rpc-flights/def.proto",
}
