[tcp.routers]
# Define a connection between requests and services
    [tcp.routers.hostSSH]
        rule = "HostSNI(`*`)"
        entrypoints = ["ssh"]
        service = "HostSSH"

[tcp.services]
    [tcp.services.HostSSH]
    # Define how to reach an existing service on our infrastructure
        [tcp.services.HostSSH.loadBalancer]
            [[tcp.services.HostSSH.loadBalancer.servers]]
                address='host_docker'
                port = 22
