[entryPoints]
  [entryPoints.db]
    address = ":5432"
  [entryPoints.web]
    address = ":80"

  [entryPoints.metrics]
    address = ":8082"

[metrics]
  [metrics.prometheus]
    addServicesLabels = true
    entryPoint = "metrics"

[api]
  dashboard = true


[providers.docker]
  watch = true
#  network = "backend" - not necessary - add if traefik cannot find the right net to talk to containers
  exposedByDefault = false

[providers.file]
  # specified as docker secret, bound in compose file and under cosmo/secrets
  directory = "/etc/traefik/dynamic"

#[providers.file]
#  filename = "traefik_dynamic.toml"