name: 'Setup networking'
description: 'Sets up an environment with Tailscale and CA certs, and grpcurl. Requires having run checkout'
inputs:
  tailscale_oauth_clientsecret:
    description: 'Tailscale oauth client secret'
    required: true
  aarch64LinuxSupport:
    description: 'Enable aarch64-linux support via QEMU'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: 'k13HPkibx421CNTRL'
        oauth-secret: ${{ inputs.tailscale_oauth_clientsecret }}
        tags: 'tag:ci-gha'

    - name: Add 2024 CA
      shell: bash
      run: |
        sudo apt-get install -y ca-certificates
        sudo cp certs/root_2024_ca.crt /usr/local/share/ca-certificates
        sudo update-ca-certificates

    - name: Set up QEMU for aarch64 support
      uses: docker/setup-qemu-action@v1
      if: inputs.aarch64LinuxSupport

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: '${{ github.token }}'
        extra_nix_config: |
          ${{ inputs.aarch64LinuxSupport && 'extra-platforms = aarch64-linux' || '' }}

    - name: Install grpcurl
      shell: bash
      run: |
        nix profile install nixpkgs#grpcurl
