// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: s-rpc-prometheus/def.proto

package s_rpc_prometheus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryInstantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromQLQuery   string                 `protobuf:"bytes,1,opt,name=promQLQuery,proto3" json:"promQLQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInstantRequest) Reset() {
	*x = QueryInstantRequest{}
	mi := &file_s_rpc_prometheus_def_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInstantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInstantRequest) ProtoMessage() {}

func (x *QueryInstantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_rpc_prometheus_def_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInstantRequest.ProtoReflect.Descriptor instead.
func (*QueryInstantRequest) Descriptor() ([]byte, []int) {
	return file_s_rpc_prometheus_def_proto_rawDescGZIP(), []int{0}
}

func (x *QueryInstantRequest) GetPromQLQuery() string {
	if x != nil {
		return x.PromQLQuery
	}
	return ""
}

type QueryInstantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInstantResponse) Reset() {
	*x = QueryInstantResponse{}
	mi := &file_s_rpc_prometheus_def_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInstantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInstantResponse) ProtoMessage() {}

func (x *QueryInstantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_rpc_prometheus_def_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInstantResponse.ProtoReflect.Descriptor instead.
func (*QueryInstantResponse) Descriptor() ([]byte, []int) {
	return file_s_rpc_prometheus_def_proto_rawDescGZIP(), []int{1}
}

func (x *QueryInstantResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *QueryInstantResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_s_rpc_prometheus_def_proto protoreflect.FileDescriptor

const file_s_rpc_prometheus_def_proto_rawDesc = "" +
	"\n" +
	"\x1as-rpc-prometheus/def.proto\x12\x10s_rpc_prometheus\x1a\x1bgoogle/protobuf/empty.proto\"7\n" +
	"\x13QueryInstantRequest\x12 \n" +
	"\vpromQLQuery\x18\x01 \x01(\tR\vpromQLQuery\"B\n" +
	"\x14QueryInstantResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type2k\n" +
	"\n" +
	"Prometheus\x12]\n" +
	"\fQueryInstant\x12%.s_rpc_prometheus.QueryInstantRequest\x1a&.s_rpc_prometheus.QueryInstantResponseB@Z>github.com/Cottand/selfosted/dev-go/lib/proto/s-rpc-prometheusb\x06proto3"

var (
	file_s_rpc_prometheus_def_proto_rawDescOnce sync.Once
	file_s_rpc_prometheus_def_proto_rawDescData []byte
)

func file_s_rpc_prometheus_def_proto_rawDescGZIP() []byte {
	file_s_rpc_prometheus_def_proto_rawDescOnce.Do(func() {
		file_s_rpc_prometheus_def_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s_rpc_prometheus_def_proto_rawDesc), len(file_s_rpc_prometheus_def_proto_rawDesc)))
	})
	return file_s_rpc_prometheus_def_proto_rawDescData
}

var file_s_rpc_prometheus_def_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_s_rpc_prometheus_def_proto_goTypes = []any{
	(*QueryInstantRequest)(nil),  // 0: s_rpc_prometheus.QueryInstantRequest
	(*QueryInstantResponse)(nil), // 1: s_rpc_prometheus.QueryInstantResponse
}
var file_s_rpc_prometheus_def_proto_depIdxs = []int32{
	0, // 0: s_rpc_prometheus.Prometheus.QueryInstant:input_type -> s_rpc_prometheus.QueryInstantRequest
	1, // 1: s_rpc_prometheus.Prometheus.QueryInstant:output_type -> s_rpc_prometheus.QueryInstantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_rpc_prometheus_def_proto_init() }
func file_s_rpc_prometheus_def_proto_init() {
	if File_s_rpc_prometheus_def_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s_rpc_prometheus_def_proto_rawDesc), len(file_s_rpc_prometheus_def_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_rpc_prometheus_def_proto_goTypes,
		DependencyIndexes: file_s_rpc_prometheus_def_proto_depIdxs,
		MessageInfos:      file_s_rpc_prometheus_def_proto_msgTypes,
	}.Build()
	File_s_rpc_prometheus_def_proto = out.File
	file_s_rpc_prometheus_def_proto_goTypes = nil
	file_s_rpc_prometheus_def_proto_depIdxs = nil
}
