// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: s-rpc-prometheus/def.proto

package s_rpc_prometheus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Prometheus_QueryInstant_FullMethodName = "/s_rpc_prometheus.Prometheus/QueryInstant"
)

// PrometheusClient is the client API for Prometheus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrometheusClient interface {
	QueryInstant(ctx context.Context, in *QueryInstantRequest, opts ...grpc.CallOption) (*QueryInstantResponse, error)
}

type prometheusClient struct {
	cc grpc.ClientConnInterface
}

func NewPrometheusClient(cc grpc.ClientConnInterface) PrometheusClient {
	return &prometheusClient{cc}
}

func (c *prometheusClient) QueryInstant(ctx context.Context, in *QueryInstantRequest, opts ...grpc.CallOption) (*QueryInstantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryInstantResponse)
	err := c.cc.Invoke(ctx, Prometheus_QueryInstant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrometheusServer is the server API for Prometheus service.
// All implementations must embed UnimplementedPrometheusServer
// for forward compatibility.
type PrometheusServer interface {
	QueryInstant(context.Context, *QueryInstantRequest) (*QueryInstantResponse, error)
	mustEmbedUnimplementedPrometheusServer()
}

// UnimplementedPrometheusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrometheusServer struct{}

func (UnimplementedPrometheusServer) QueryInstant(context.Context, *QueryInstantRequest) (*QueryInstantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryInstant not implemented")
}
func (UnimplementedPrometheusServer) mustEmbedUnimplementedPrometheusServer() {}
func (UnimplementedPrometheusServer) testEmbeddedByValue()                    {}

// UnsafePrometheusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrometheusServer will
// result in compilation errors.
type UnsafePrometheusServer interface {
	mustEmbedUnimplementedPrometheusServer()
}

func RegisterPrometheusServer(s grpc.ServiceRegistrar, srv PrometheusServer) {
	// If the following call panics, it indicates UnimplementedPrometheusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Prometheus_ServiceDesc, srv)
}

func _Prometheus_QueryInstant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInstantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrometheusServer).QueryInstant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prometheus_QueryInstant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrometheusServer).QueryInstant(ctx, req.(*QueryInstantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Prometheus_ServiceDesc is the grpc.ServiceDesc for Prometheus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prometheus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s_rpc_prometheus.Prometheus",
	HandlerType: (*PrometheusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryInstant",
			Handler:    _Prometheus_QueryInstant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s-rpc-prometheus/def.proto",
}
