// Code generated by protocplugin. DO NOT EDIT.

package s_rpc_prometheus

import (
	context "context"
	bedrock "github.com/cottand/selfhosted/dev-go/lib/bedrock"
	grpc "google.golang.org/grpc"
	sync "sync"
)

var loadClient = sync.OnceValues(func() (PrometheusClient, error) {
	conn, err := bedrock.NewGrpcConn()
	if err != nil {
		return nil, err
	}
	return NewPrometheusClient(conn), nil
})

func QueryInstant(ctx context.Context, in *QueryInstantRequest, opts ...grpc.CallOption) (*QueryInstantResponse, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.QueryInstant(ctx, in, opts...)
}
