name: 'Setup build environment'
description: 'Sets up an environment with Nix and attic caching. Requires having run checkout'
inputs:
  tailscale_oauth_clientsecret:
    description: 'Tailscale oauth client secret'
    required: true
  aarch64LinuxSupport:
    description: 'Enable aarch64-linux support via QEMU'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-networking
      name: Set up networking
      with:
        tailscale_oauth_clientsecret: ${{ inputs.tailscale_oauth_clientsecret }}
        aarch64LinuxSupport: ${{ inputs.aarch64LinuxSupport }}

    - name: Read CA
      id: read_ca
      shell: bash
      run: |
        echo 'CA_BASE_64<<EOF' >> $GITHUB_OUTPUT
        cat certs/root_2024_ca.crt | base64 >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.dcotta.com:8200
        role: actions-ro
        path: jwt-github
        method: jwt
        jwtGithubAudience: sigstore
        caCertificate: ${{ steps.read_ca.outputs.CA_BASE_64 }}
        secrets: |
          secret/data/nomad/job/attic/users/github-actions value | ATTIC_TOKEN ;

    - name: Install Attic and nix-fast-build
      shell: bash
      run: |
        nix profile add nixpkgs#attic-client nixpkgs#nix-fast-build

    - name: Configure Attic
      shell: bash
      run: |
        attic login --set-default central "$ATTIC_SERVER" "$ATTIC_TOKEN"
        attic use "$ATTIC_CACHE"
      env:
        ATTIC_TOKEN: ${{ steps.secrets.outputs.ATTIC_TOKEN }}