// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: s-rpc-portfolio-stats/def.proto

package s_rpc_portfolio_stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Visit) Reset() {
	*x = Visit{}
	mi := &file_s_rpc_portfolio_stats_def_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Visit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visit) ProtoMessage() {}

func (x *Visit) ProtoReflect() protoreflect.Message {
	mi := &file_s_rpc_portfolio_stats_def_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visit.ProtoReflect.Descriptor instead.
func (*Visit) Descriptor() ([]byte, []int) {
	return file_s_rpc_portfolio_stats_def_proto_rawDescGZIP(), []int{0}
}

func (x *Visit) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Visit) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Visit) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Visit) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

var File_s_rpc_portfolio_stats_def_proto protoreflect.FileDescriptor

const file_s_rpc_portfolio_stats_def_proto_rawDesc = "" +
	"\n" +
	"\x1fs-rpc-portfolio-stats/def.proto\x12\x15s_rpc_portfolio_stats\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n" +
	"\x05Visit\x12=\n" +
	"\flast_updated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1c\n" +
	"\tuserAgent\x18\x04 \x01(\tR\tuserAgent2R\n" +
	"\x0ePortfolioStats\x12@\n" +
	"\x06Report\x12\x1c.s_rpc_portfolio_stats.Visit\x1a\x16.google.protobuf.Empty\"\x00BEZCgithub.com/Cottand/selfosted/dev-go/lib/proto/s-rpc-portfolio-statsb\x06proto3"

var (
	file_s_rpc_portfolio_stats_def_proto_rawDescOnce sync.Once
	file_s_rpc_portfolio_stats_def_proto_rawDescData []byte
)

func file_s_rpc_portfolio_stats_def_proto_rawDescGZIP() []byte {
	file_s_rpc_portfolio_stats_def_proto_rawDescOnce.Do(func() {
		file_s_rpc_portfolio_stats_def_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s_rpc_portfolio_stats_def_proto_rawDesc), len(file_s_rpc_portfolio_stats_def_proto_rawDesc)))
	})
	return file_s_rpc_portfolio_stats_def_proto_rawDescData
}

var file_s_rpc_portfolio_stats_def_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_s_rpc_portfolio_stats_def_proto_goTypes = []any{
	(*Visit)(nil),                 // 0: s_rpc_portfolio_stats.Visit
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_s_rpc_portfolio_stats_def_proto_depIdxs = []int32{
	1, // 0: s_rpc_portfolio_stats.Visit.last_updated:type_name -> google.protobuf.Timestamp
	0, // 1: s_rpc_portfolio_stats.PortfolioStats.Report:input_type -> s_rpc_portfolio_stats.Visit
	2, // 2: s_rpc_portfolio_stats.PortfolioStats.Report:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_s_rpc_portfolio_stats_def_proto_init() }
func file_s_rpc_portfolio_stats_def_proto_init() {
	if File_s_rpc_portfolio_stats_def_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s_rpc_portfolio_stats_def_proto_rawDesc), len(file_s_rpc_portfolio_stats_def_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_rpc_portfolio_stats_def_proto_goTypes,
		DependencyIndexes: file_s_rpc_portfolio_stats_def_proto_depIdxs,
		MessageInfos:      file_s_rpc_portfolio_stats_def_proto_msgTypes,
	}.Build()
	File_s_rpc_portfolio_stats_def_proto = out.File
	file_s_rpc_portfolio_stats_def_proto_goTypes = nil
	file_s_rpc_portfolio_stats_def_proto_depIdxs = nil
}
