// Code generated by protocplugin. DO NOT EDIT.

package s_rpc_portfolio_stats

import (
	context "context"
	bedrock "github.com/cottand/selfhosted/dev-go/lib/bedrock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sync "sync"
)

var loadClient = sync.OnceValues(func() (PortfolioStatsClient, error) {
	conn, err := bedrock.NewGrpcConn()
	if err != nil {
		return nil, err
	}
	return NewPortfolioStatsClient(conn), nil
})

func Report(ctx context.Context, in *Visit, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.Report(ctx, in, opts...)
}
