port: 53
httpPort: 4000
upstream:
  default:
    # DNS over TCP https://blog.uncensoreddns.org/dns-servers/
    - 91.239.100.100:843
    - 9.9.9.9
    - 1.1.1.1
#    - https://dns.digitale-gesellschaft.ch/dns-query

customDNS:
  customTTL: 5m
  rewrite:
    vps.dcotta.eu: host.vps
    web.vps.dcotta.eu: host.vps
  mapping:
    # address of traefik + wg network. Requests to this IP will hit the traefik proxy which will route
    # containers appropriately
    host.vps: 10.8.0.1

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
  clientGroupsBlock:
    default:
      - ads

prometheus:
  enable: true