// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: s-rpc-autoscaler/def.proto

package s_rpc_autoscaler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalingStrategy int32

const (
	ScalingStrategy_None  ScalingStrategy = 0
	ScalingStrategy_Basic ScalingStrategy = 1
)

// Enum value maps for ScalingStrategy.
var (
	ScalingStrategy_name = map[int32]string{
		0: "None",
		1: "Basic",
	}
	ScalingStrategy_value = map[string]int32{
		"None":  0,
		"Basic": 1,
	}
)

func (x ScalingStrategy) Enum() *ScalingStrategy {
	p := new(ScalingStrategy)
	*p = x
	return p
}

func (x ScalingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_s_rpc_autoscaler_def_proto_enumTypes[0].Descriptor()
}

func (ScalingStrategy) Type() protoreflect.EnumType {
	return &file_s_rpc_autoscaler_def_proto_enumTypes[0]
}

func (x ScalingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingStrategy.Descriptor instead.
func (ScalingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_s_rpc_autoscaler_def_proto_rawDescGZIP(), []int{0}
}

type EvalAllScalingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalAllScalingStatusResponse) Reset() {
	*x = EvalAllScalingStatusResponse{}
	mi := &file_s_rpc_autoscaler_def_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalAllScalingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalAllScalingStatusResponse) ProtoMessage() {}

func (x *EvalAllScalingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_rpc_autoscaler_def_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalAllScalingStatusResponse.ProtoReflect.Descriptor instead.
func (*EvalAllScalingStatusResponse) Descriptor() ([]byte, []int) {
	return file_s_rpc_autoscaler_def_proto_rawDescGZIP(), []int{0}
}

var File_s_rpc_autoscaler_def_proto protoreflect.FileDescriptor

const file_s_rpc_autoscaler_def_proto_rawDesc = "" +
	"\n" +
	"\x1as-rpc-autoscaler/def.proto\x12\x10s_rpc_autoscaler\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\x1cEvalAllScalingStatusResponse*&\n" +
	"\x0fScalingStrategy\x12\b\n" +
	"\x04None\x10\x00\x12\t\n" +
	"\x05Basic\x10\x012l\n" +
	"\n" +
	"Autoscaler\x12^\n" +
	"\x14EvalAllScalingStatus\x12\x16.google.protobuf.Empty\x1a..s_rpc_autoscaler.EvalAllScalingStatusResponseB@Z>github.com/Cottand/selfosted/dev-go/lib/proto/s-rpc-autoscalerb\x06proto3"

var (
	file_s_rpc_autoscaler_def_proto_rawDescOnce sync.Once
	file_s_rpc_autoscaler_def_proto_rawDescData []byte
)

func file_s_rpc_autoscaler_def_proto_rawDescGZIP() []byte {
	file_s_rpc_autoscaler_def_proto_rawDescOnce.Do(func() {
		file_s_rpc_autoscaler_def_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s_rpc_autoscaler_def_proto_rawDesc), len(file_s_rpc_autoscaler_def_proto_rawDesc)))
	})
	return file_s_rpc_autoscaler_def_proto_rawDescData
}

var file_s_rpc_autoscaler_def_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_s_rpc_autoscaler_def_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_s_rpc_autoscaler_def_proto_goTypes = []any{
	(ScalingStrategy)(0),                 // 0: s_rpc_autoscaler.ScalingStrategy
	(*EvalAllScalingStatusResponse)(nil), // 1: s_rpc_autoscaler.EvalAllScalingStatusResponse
	(*emptypb.Empty)(nil),                // 2: google.protobuf.Empty
}
var file_s_rpc_autoscaler_def_proto_depIdxs = []int32{
	2, // 0: s_rpc_autoscaler.Autoscaler.EvalAllScalingStatus:input_type -> google.protobuf.Empty
	1, // 1: s_rpc_autoscaler.Autoscaler.EvalAllScalingStatus:output_type -> s_rpc_autoscaler.EvalAllScalingStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_rpc_autoscaler_def_proto_init() }
func file_s_rpc_autoscaler_def_proto_init() {
	if File_s_rpc_autoscaler_def_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s_rpc_autoscaler_def_proto_rawDesc), len(file_s_rpc_autoscaler_def_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_rpc_autoscaler_def_proto_goTypes,
		DependencyIndexes: file_s_rpc_autoscaler_def_proto_depIdxs,
		EnumInfos:         file_s_rpc_autoscaler_def_proto_enumTypes,
		MessageInfos:      file_s_rpc_autoscaler_def_proto_msgTypes,
	}.Build()
	File_s_rpc_autoscaler_def_proto = out.File
	file_s_rpc_autoscaler_def_proto_goTypes = nil
	file_s_rpc_autoscaler_def_proto_depIdxs = nil
}
