// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: s-rpc-autoscaler/def.proto

package s_rpc_autoscaler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Autoscaler_EvalAllScalingStatus_FullMethodName = "/s_rpc_autoscaler.Autoscaler/EvalAllScalingStatus"
)

// AutoscalerClient is the client API for Autoscaler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoscalerClient interface {
	EvalAllScalingStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EvalAllScalingStatusResponse, error)
}

type autoscalerClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoscalerClient(cc grpc.ClientConnInterface) AutoscalerClient {
	return &autoscalerClient{cc}
}

func (c *autoscalerClient) EvalAllScalingStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EvalAllScalingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvalAllScalingStatusResponse)
	err := c.cc.Invoke(ctx, Autoscaler_EvalAllScalingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoscalerServer is the server API for Autoscaler service.
// All implementations must embed UnimplementedAutoscalerServer
// for forward compatibility.
type AutoscalerServer interface {
	EvalAllScalingStatus(context.Context, *emptypb.Empty) (*EvalAllScalingStatusResponse, error)
	mustEmbedUnimplementedAutoscalerServer()
}

// UnimplementedAutoscalerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutoscalerServer struct{}

func (UnimplementedAutoscalerServer) EvalAllScalingStatus(context.Context, *emptypb.Empty) (*EvalAllScalingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvalAllScalingStatus not implemented")
}
func (UnimplementedAutoscalerServer) mustEmbedUnimplementedAutoscalerServer() {}
func (UnimplementedAutoscalerServer) testEmbeddedByValue()                    {}

// UnsafeAutoscalerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoscalerServer will
// result in compilation errors.
type UnsafeAutoscalerServer interface {
	mustEmbedUnimplementedAutoscalerServer()
}

func RegisterAutoscalerServer(s grpc.ServiceRegistrar, srv AutoscalerServer) {
	// If the following call panics, it indicates UnimplementedAutoscalerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Autoscaler_ServiceDesc, srv)
}

func _Autoscaler_EvalAllScalingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoscalerServer).EvalAllScalingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Autoscaler_EvalAllScalingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoscalerServer).EvalAllScalingStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Autoscaler_ServiceDesc is the grpc.ServiceDesc for Autoscaler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Autoscaler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s_rpc_autoscaler.Autoscaler",
	HandlerType: (*AutoscalerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvalAllScalingStatus",
			Handler:    _Autoscaler_EvalAllScalingStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s-rpc-autoscaler/def.proto",
}
