#macofile: noinspection SpellCheckingInspection
version: '3.9'

name: maco

services:
  wg-client:
    image: linuxserver/wireguard:alpine
    restart: unless-stopped
    extra_hosts: ['host_docker:172.18.0.1 ']
    volumes:
      - ./wg:/config
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    environment:
      IPTABLES_MASQ: '0'
  nomad:
    build: nomad/image
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      #- /var/run/:/var/run/:shared
      #- /var/run/docker.sock:/var/run/docker.sock:shared
      - /var/run/docker/netns/:/var/run/docker/netns/:shared
      - /var/run/docker.sock:/var/run/docker.sock:share
      - ./nomad/config:/etc/config
      - ./nomad/data:/var/lib/nomad
      - ./nomad/client-state:/var/lib/nomad-client-state
      # must be absolute paths because nomad mounts these itself
      - /home/cottand/selfhosted/maco/volumes/:/home/cottand/selfhosted/maco/volumes/
      - /home/cottand/selfhosted/maco/nomad/alloc/:/home/cottand/selfhosted/maco/nomad/alloc
