version: '3.9'

name: maco
networks:
  wg:
    ipam:
      config:
        # subnet CIDR hardcoded in
        # maco is reserved for addresses only above 10.8.1.100
        - subnet: 10.8.1.0/24

services:
#  cloudflared:
#    image: cloudflare/cloudflared:latest
#    command: tunnel run --no-autoupdate
#    env_file:
#      - secrets/cloudflared.env

  wg-client:
    image: cmulk/wireguard-docker:alpine
    restart: unless-stopped
    volumes:
      - ./wg:/etc/wireguard
    networks:
      - net
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  whoami:
    image: traefik/whoami
    command:
      - --port=80
    ports:
      - '80:80'
    networks:
      wg:
        ipv4_address: 10.8.1.101
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`web.vps.dcotta.eu`) && PathPrefix(`/whoami`)
      traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes: /whoami
      traefik.http.services.whoami.loadbalancer.server.port: 80
      traefik.http.routers.whoami.middlewares: whoami-stripprefix,auth@file
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls: true

