version: '3.9'


services:
  nomad:
    build: nomad/image
    network_mode: host
    privileged: true
    restart: unless-stopped
    depends_on: [temp-wireguard]
    volumes:
      - /var/run/docker/netns/:/var/run/docker/netns/:shared
      - /var/run/docker.sock:/var/run/docker.sock:share
      - ./nomad/config:/etc/config
      - ./nomad/data:/var/lib/nomad
      - ./nomad/client-state:/var/lib/nomad-client-state
      # must be absolute paths because nomad mounts these itself
      - /root/selfhosted/cosmo/volumes/:/root/selfhosted/cosmo/volumes/
      - /root/selfhosted/cosmo/nomad/alloc/:/root/selfhosted/cosmo/nomad/alloc

  # bootstraps the network nomad is running in. Can't be a nomad job because it needs
  # to be up for the server to advertise itself in the network
  temp-wireguard:
    # ports: 51820 for WG
    #        51821 for wg-easy
    image: weejewel/wg-easy
    container_name: wg-easy
    restart: unless-stopped
    environment:
      WG_HOST: vps.dcotta.eu

      WG_DEFAULT_DNS: 10.8.0.1
      # see https://github.com/WeeJeWel/wg-easy/blob/master/src/config.js
      #
    volumes:
      - ./wg:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
