package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, file := range gen.Files {
			if !file.Generate {
				continue
			}
			generateFile(gen, file)
		}
		return nil
	})
}

const (
	contextPackage = protogen.GoImportPath("context")
	grpcPackage    = protogen.GoImportPath("google.golang.org/grpc")
	syncPackage    = protogen.GoImportPath("sync")
	codesPackage   = protogen.GoImportPath("google.golang.org/grpc/codes")
	statusPackage  = protogen.GoImportPath("google.golang.org/grpc/status")

	bedrockPackage = protogen.GoImportPath("github.com/cottand/selfhosted/dev-go/lib/bedrock")
)

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	filename := file.GeneratedFilenamePrefix + "_devgo.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protocplugin. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	if err := loadClientFunc(g, file.Services[0]); err != nil {
		return err
	}

	for _, service := range file.Services {
		for _, method := range service.Methods {
			if err := clientCall(g, method); err != nil {
				return err
			}
		}
	}

	return nil
}

/*
var loadClient = sync.OnceValues(func() (AutoscalerClient, error) {
	conn, err := bedrock.NewGrpcConn()
	if err != nil {
		return nil, err
	}
	return NewAutoscalerClient(conn), nil
})

func EvalAllScalingStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EvalAllScalingStatusResponse, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.EvalAllScalingStatus(ctx, in, opts...)
}

*/

func loadClientFunc(g *protogen.GeneratedFile, service *protogen.Service) error {
	// client interface
	clientName := service.GoName + "Client"

	s := fmt.Sprintf("var loadClient = %s(func() (%s, error) {", g.QualifiedGoIdent(syncPackage.Ident("OnceValues")), clientName)
	g.P(s)
	g.P("conn, err := ", g.QualifiedGoIdent(bedrockPackage.Ident("NewGrpcConn")), "()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("return ", "New", clientName, "(conn), nil")
	g.P("})")

	return nil
}

func clientCall(g *protogen.GeneratedFile, method *protogen.Method) error {
	s := method.Comments.Leading.String() + "func " + method.GoName + "(ctx " + g.QualifiedGoIdent(contextPackage.Ident("Context"))

	if !method.Desc.IsStreamingClient() {
		s += ", in *" + g.QualifiedGoIdent(method.Input.GoIdent)
	}
	s += ", opts ..." + g.QualifiedGoIdent(grpcPackage.Ident("CallOption")) + ") ("
	if !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
		s += "*" + g.QualifiedGoIdent(method.Output.GoIdent)
	} else {
		s += clientStreamInterface(g, method)
	}
	s += ", error) {"
	g.P(s)

	g.P("client, err := loadClient()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	if !method.Desc.IsStreamingClient() {
		g.P("return client.", method.GoName, "(ctx, in, opts...)")
	} else {
		return fmt.Errorf("streaming client not implemented yet: %s", method.GoName)
	}

	g.P("}")
	g.P()

	return nil
}

func clientStreamInterface(g *protogen.GeneratedFile, method *protogen.Method) string {
	typeParam := g.QualifiedGoIdent(method.Input.GoIdent) + ", " + g.QualifiedGoIdent(method.Output.GoIdent)
	if method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer() {
		return g.QualifiedGoIdent(grpcPackage.Ident("BidiStreamingClient")) + "[" + typeParam + "]"
	}
	if method.Desc.IsStreamingClient() {
		return g.QualifiedGoIdent(grpcPackage.Ident("ClientStreamingClient")) + "[" + typeParam + "]"
	}
	return g.QualifiedGoIdent(grpcPackage.Ident("ServerStreamingClient")) + "[" + g.QualifiedGoIdent(method.Output.GoIdent) + "]"
}
