// Code generated by protocplugin. DO NOT EDIT.

package s_rpc_vault

import (
	context "context"
	bedrock "github.com/cottand/selfhosted/dev-go/lib/bedrock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sync "sync"
)

var loadClient = sync.OnceValues(func() (MqttClient, error) {
	conn, err := bedrock.NewGrpcConn()
	if err != nil {
		return nil, err
	}
	return NewMqttClient(conn), nil
})

func Dummy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.Dummy(ctx, in, opts...)
}
