// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: s-rpc-mqtt/def.proto

package s_rpc_vault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mqtt_Dummy_FullMethodName = "/s_rpc_vault.Mqtt/Dummy"
)

// MqttClient is the client API for Mqtt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MqttClient interface {
	Dummy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mqttClient struct {
	cc grpc.ClientConnInterface
}

func NewMqttClient(cc grpc.ClientConnInterface) MqttClient {
	return &mqttClient{cc}
}

func (c *mqttClient) Dummy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Mqtt_Dummy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MqttServer is the server API for Mqtt service.
// All implementations must embed UnimplementedMqttServer
// for forward compatibility.
type MqttServer interface {
	Dummy(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedMqttServer()
}

// UnimplementedMqttServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMqttServer struct{}

func (UnimplementedMqttServer) Dummy(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Dummy not implemented")
}
func (UnimplementedMqttServer) mustEmbedUnimplementedMqttServer() {}
func (UnimplementedMqttServer) testEmbeddedByValue()              {}

// UnsafeMqttServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MqttServer will
// result in compilation errors.
type UnsafeMqttServer interface {
	mustEmbedUnimplementedMqttServer()
}

func RegisterMqttServer(s grpc.ServiceRegistrar, srv MqttServer) {
	// If the following call panics, it indicates UnimplementedMqttServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mqtt_ServiceDesc, srv)
}

func _Mqtt_Dummy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttServer).Dummy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mqtt_Dummy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttServer).Dummy(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Mqtt_ServiceDesc is the grpc.ServiceDesc for Mqtt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mqtt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s_rpc_vault.Mqtt",
	HandlerType: (*MqttServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dummy",
			Handler:    _Mqtt_Dummy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s-rpc-mqtt/def.proto",
}
