name: check

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

env:
  ATTIC_SERVER: "https://attic.tfk.nd/"
  ATTIC_CACHE: "default"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build-env
        name: Set up build env
        with:
          caCertificate: ${{ secrets.DCOTTA_ROOT_CA }}
          tailscale_oauth_clientsecret: ${{ secrets.TAILSCALE_OAUTH_CLIENTSECRET }}
      - name: Flake check
        run: |
          # runs checks by default
          nix-fast-build --eval-workers 1 --skip-cached --no-nom
