name: Build Images

on:
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY_IMAGE: "ghcr.io/cottand/selfhosted"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build images
        run: |
          nix build -L .#scripts.all-images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install skopeo
        run: |
          nix profile install nixpkgs#skopeo nixpkgs#python3

      - name: Push images
        shell: python
        run: |
          import os
          import json
          
          
          images = os.popen("jq < $(nix build .#scripts.all-images --print-out-paths)").read()
          git_sha = os.popen('git rev-parse --short "$GITHUB_SHA"').read()
          
          for tag, path in json.loads(images).items():
            print("got k="+tag+" and v="+path)

