name: Build Images

on:
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY_IMAGE: "ghcr.io/cottand/selfhosted"

jobs:
  generate-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: codegen CI
        run: |
          nix build .#gh-ci -L
          
          cp result .github/workflows/gh-ci-generated.yml

  run-generated:
    needs: [ generate-ci ]
    uses: ./.github/workflows/gh-ci-generated.yml

