[entryPoints]

  [entryPoints.db]
    address = ":5432"
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
#
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.metrics]
    address = ":8082"

[metrics]
  [metrics.prometheus]
    addServicesLabels = true
    entryPoint = "metrics"

[api]
  dashboard = true
  insecure = false



[certificatesResolvers.lets-encrypt.acme]
  email = "nico@dcotta.eu"
  storage = "/etc/traefik/acme.json"

  [certificatesResolvers.lets-encrypt.acme.httpChallenge]
    # let's encrypt has to be able to reach on this entrypoint for cert
    entryPoint = "web"


[providers.docker]
  watch = true
#  network = "backend"
  exposedByDefault = false

[providers.file]
  # specified as docker secret, bound in compose file and under cosmo/secrets
  directory = "/run/secrets/traefik_secret.toml"

#[providers.file]
#  filename = "traefik_dynamic.toml"