// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: s-rpc-nomad-api/def.proto

package s_rpc_nomad_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*Job_Commit
	//	*Job_Latest
	Version       isJob_Version `protobuf_oneof:"Version"`
	Name          string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_s_rpc_nomad_api_def_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_s_rpc_nomad_api_def_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_s_rpc_nomad_api_def_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetVersion() isJob_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Job) GetCommit() string {
	if x != nil {
		if x, ok := x.Version.(*Job_Commit); ok {
			return x.Commit
		}
	}
	return ""
}

func (x *Job) GetLatest() bool {
	if x != nil {
		if x, ok := x.Version.(*Job_Latest); ok {
			return x.Latest
		}
	}
	return false
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type isJob_Version interface {
	isJob_Version()
}

type Job_Commit struct {
	Commit string `protobuf:"bytes,1,opt,name=commit,proto3,oneof"`
}

type Job_Latest struct {
	Latest bool `protobuf:"varint,2,opt,name=latest,proto3,oneof"`
}

func (*Job_Commit) isJob_Version() {}

func (*Job_Latest) isJob_Version() {}

var File_s_rpc_nomad_api_def_proto protoreflect.FileDescriptor

const file_s_rpc_nomad_api_def_proto_rawDesc = "" +
	"\n" +
	"\x19s-rpc-nomad-api/def.proto\x12\x0fs_rpc_nomad_api\x1a\x1bgoogle/protobuf/empty.proto\"X\n" +
	"\x03Job\x12\x18\n" +
	"\x06commit\x18\x01 \x01(\tH\x00R\x06commit\x12\x18\n" +
	"\x06latest\x18\x02 \x01(\bH\x00R\x06latest\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB\t\n" +
	"\aVersion2D\n" +
	"\bNomadApi\x128\n" +
	"\x06Deploy\x12\x14.s_rpc_nomad_api.Job\x1a\x16.google.protobuf.Empty\"\x00B?Z=github.com/Cottand/selfosted/dev-go/lib/proto/s-rpc-nomad-apib\x06proto3"

var (
	file_s_rpc_nomad_api_def_proto_rawDescOnce sync.Once
	file_s_rpc_nomad_api_def_proto_rawDescData []byte
)

func file_s_rpc_nomad_api_def_proto_rawDescGZIP() []byte {
	file_s_rpc_nomad_api_def_proto_rawDescOnce.Do(func() {
		file_s_rpc_nomad_api_def_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s_rpc_nomad_api_def_proto_rawDesc), len(file_s_rpc_nomad_api_def_proto_rawDesc)))
	})
	return file_s_rpc_nomad_api_def_proto_rawDescData
}

var file_s_rpc_nomad_api_def_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_s_rpc_nomad_api_def_proto_goTypes = []any{
	(*Job)(nil),           // 0: s_rpc_nomad_api.Job
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_s_rpc_nomad_api_def_proto_depIdxs = []int32{
	0, // 0: s_rpc_nomad_api.NomadApi.Deploy:input_type -> s_rpc_nomad_api.Job
	1, // 1: s_rpc_nomad_api.NomadApi.Deploy:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_rpc_nomad_api_def_proto_init() }
func file_s_rpc_nomad_api_def_proto_init() {
	if File_s_rpc_nomad_api_def_proto != nil {
		return
	}
	file_s_rpc_nomad_api_def_proto_msgTypes[0].OneofWrappers = []any{
		(*Job_Commit)(nil),
		(*Job_Latest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s_rpc_nomad_api_def_proto_rawDesc), len(file_s_rpc_nomad_api_def_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_rpc_nomad_api_def_proto_goTypes,
		DependencyIndexes: file_s_rpc_nomad_api_def_proto_depIdxs,
		MessageInfos:      file_s_rpc_nomad_api_def_proto_msgTypes,
	}.Build()
	File_s_rpc_nomad_api_def_proto = out.File
	file_s_rpc_nomad_api_def_proto_goTypes = nil
	file_s_rpc_nomad_api_def_proto_depIdxs = nil
}
