// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: s-rpc-nomad-api/def.proto

package s_rpc_nomad_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Version:
	//
	//	*Job_Commit
	//	*Job_Latest
	Version       isJob_Version `protobuf_oneof:"Version"`
	JobPathInRepo string        `protobuf:"bytes,3,opt,name=jobPathInRepo,proto3" json:"jobPathInRepo,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_rpc_nomad_api_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_s_rpc_nomad_api_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_s_rpc_nomad_api_def_proto_rawDescGZIP(), []int{0}
}

func (m *Job) GetVersion() isJob_Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (x *Job) GetCommit() string {
	if x, ok := x.GetVersion().(*Job_Commit); ok {
		return x.Commit
	}
	return ""
}

func (x *Job) GetLatest() bool {
	if x, ok := x.GetVersion().(*Job_Latest); ok {
		return x.Latest
	}
	return false
}

func (x *Job) GetJobPathInRepo() string {
	if x != nil {
		return x.JobPathInRepo
	}
	return ""
}

type isJob_Version interface {
	isJob_Version()
}

type Job_Commit struct {
	Commit string `protobuf:"bytes,1,opt,name=commit,proto3,oneof"`
}

type Job_Latest struct {
	Latest bool `protobuf:"varint,2,opt,name=latest,proto3,oneof"`
}

func (*Job_Commit) isJob_Version() {}

func (*Job_Latest) isJob_Version() {}

var File_s_rpc_nomad_api_def_proto protoreflect.FileDescriptor

var file_s_rpc_nomad_api_def_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x2d, 0x72, 0x70, 0x63, 0x2d, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x5f, 0x72,
	0x70, 0x63, 0x5f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x03, 0x4a, 0x6f, 0x62,
	0x12, 0x18, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6a, 0x6f, 0x62, 0x50, 0x61, 0x74, 0x68, 0x49,
	0x6e, 0x52, 0x65, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6a, 0x6f, 0x62,
	0x50, 0x61, 0x74, 0x68, 0x49, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x44, 0x0a, 0x08, 0x4e, 0x6f, 0x6d, 0x61, 0x64, 0x41, 0x70,
	0x69, 0x12, 0x38, 0x0a, 0x06, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x14, 0x2e, 0x73, 0x5f,
	0x72, 0x70, 0x63, 0x5f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f,
	0x62, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x3d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x74, 0x74, 0x61, 0x6e,
	0x64, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x2f, 0x64, 0x65, 0x76, 0x2d,
	0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x2d, 0x72,
	0x70, 0x63, 0x2d, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_rpc_nomad_api_def_proto_rawDescOnce sync.Once
	file_s_rpc_nomad_api_def_proto_rawDescData = file_s_rpc_nomad_api_def_proto_rawDesc
)

func file_s_rpc_nomad_api_def_proto_rawDescGZIP() []byte {
	file_s_rpc_nomad_api_def_proto_rawDescOnce.Do(func() {
		file_s_rpc_nomad_api_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_rpc_nomad_api_def_proto_rawDescData)
	})
	return file_s_rpc_nomad_api_def_proto_rawDescData
}

var file_s_rpc_nomad_api_def_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_s_rpc_nomad_api_def_proto_goTypes = []any{
	(*Job)(nil),           // 0: s_rpc_nomad_api.Job
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_s_rpc_nomad_api_def_proto_depIdxs = []int32{
	0, // 0: s_rpc_nomad_api.NomadApi.Deploy:input_type -> s_rpc_nomad_api.Job
	1, // 1: s_rpc_nomad_api.NomadApi.Deploy:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_rpc_nomad_api_def_proto_init() }
func file_s_rpc_nomad_api_def_proto_init() {
	if File_s_rpc_nomad_api_def_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_rpc_nomad_api_def_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_s_rpc_nomad_api_def_proto_msgTypes[0].OneofWrappers = []any{
		(*Job_Commit)(nil),
		(*Job_Latest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_rpc_nomad_api_def_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_rpc_nomad_api_def_proto_goTypes,
		DependencyIndexes: file_s_rpc_nomad_api_def_proto_depIdxs,
		MessageInfos:      file_s_rpc_nomad_api_def_proto_msgTypes,
	}.Build()
	File_s_rpc_nomad_api_def_proto = out.File
	file_s_rpc_nomad_api_def_proto_rawDesc = nil
	file_s_rpc_nomad_api_def_proto_goTypes = nil
	file_s_rpc_nomad_api_def_proto_depIdxs = nil
}
