// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: s-rpc-nomad-api/def.proto

package s_rpc_nomad_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NomadApi_Deploy_FullMethodName             = "/s_rpc_nomad_api.NomadApi/Deploy"
	NomadApi_ListJobDefinitions_FullMethodName = "/s_rpc_nomad_api.NomadApi/ListJobDefinitions"
	NomadApi_ReadJobDefinition_FullMethodName  = "/s_rpc_nomad_api.NomadApi/ReadJobDefinition"
)

// NomadApiClient is the client API for NomadApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NomadApiClient interface {
	// Deploy deploys a job from a Nix definition
	Deploy(ctx context.Context, in *Job, opts ...grpc.CallOption) (*DeployResponse, error)
	ListJobDefinitions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error)
	ReadJobDefinition(ctx context.Context, in *ReadJobDefinitionRequest, opts ...grpc.CallOption) (*ReadJobDefinitionResponse, error)
}

type nomadApiClient struct {
	cc grpc.ClientConnInterface
}

func NewNomadApiClient(cc grpc.ClientConnInterface) NomadApiClient {
	return &nomadApiClient{cc}
}

func (c *nomadApiClient) Deploy(ctx context.Context, in *Job, opts ...grpc.CallOption) (*DeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, NomadApi_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomadApiClient) ListJobDefinitions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NomadApi_ServiceDesc.Streams[0], NomadApi_ListJobDefinitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ListJobsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NomadApi_ListJobDefinitionsClient = grpc.ServerStreamingClient[ListJobsResponse]

func (c *nomadApiClient) ReadJobDefinition(ctx context.Context, in *ReadJobDefinitionRequest, opts ...grpc.CallOption) (*ReadJobDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadJobDefinitionResponse)
	err := c.cc.Invoke(ctx, NomadApi_ReadJobDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NomadApiServer is the server API for NomadApi service.
// All implementations must embed UnimplementedNomadApiServer
// for forward compatibility.
type NomadApiServer interface {
	// Deploy deploys a job from a Nix definition
	Deploy(context.Context, *Job) (*DeployResponse, error)
	ListJobDefinitions(*emptypb.Empty, grpc.ServerStreamingServer[ListJobsResponse]) error
	ReadJobDefinition(context.Context, *ReadJobDefinitionRequest) (*ReadJobDefinitionResponse, error)
	mustEmbedUnimplementedNomadApiServer()
}

// UnimplementedNomadApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNomadApiServer struct{}

func (UnimplementedNomadApiServer) Deploy(context.Context, *Job) (*DeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedNomadApiServer) ListJobDefinitions(*emptypb.Empty, grpc.ServerStreamingServer[ListJobsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListJobDefinitions not implemented")
}
func (UnimplementedNomadApiServer) ReadJobDefinition(context.Context, *ReadJobDefinitionRequest) (*ReadJobDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadJobDefinition not implemented")
}
func (UnimplementedNomadApiServer) mustEmbedUnimplementedNomadApiServer() {}
func (UnimplementedNomadApiServer) testEmbeddedByValue()                  {}

// UnsafeNomadApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NomadApiServer will
// result in compilation errors.
type UnsafeNomadApiServer interface {
	mustEmbedUnimplementedNomadApiServer()
}

func RegisterNomadApiServer(s grpc.ServiceRegistrar, srv NomadApiServer) {
	// If the following call panics, it indicates UnimplementedNomadApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NomadApi_ServiceDesc, srv)
}

func _NomadApi_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadApiServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadApi_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadApiServer).Deploy(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _NomadApi_ListJobDefinitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NomadApiServer).ListJobDefinitions(m, &grpc.GenericServerStream[emptypb.Empty, ListJobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NomadApi_ListJobDefinitionsServer = grpc.ServerStreamingServer[ListJobsResponse]

func _NomadApi_ReadJobDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJobDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadApiServer).ReadJobDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadApi_ReadJobDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadApiServer).ReadJobDefinition(ctx, req.(*ReadJobDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NomadApi_ServiceDesc is the grpc.ServiceDesc for NomadApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NomadApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s_rpc_nomad_api.NomadApi",
	HandlerType: (*NomadApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _NomadApi_Deploy_Handler,
		},
		{
			MethodName: "ReadJobDefinition",
			Handler:    _NomadApi_ReadJobDefinition_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListJobDefinitions",
			Handler:       _NomadApi_ListJobDefinitions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "s-rpc-nomad-api/def.proto",
}
