// Code generated by protocplugin. DO NOT EDIT.

package s_rpc_nomad_api

import (
	context "context"
	bedrock "github.com/cottand/selfhosted/dev-go/lib/bedrock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sync "sync"
)

var loadClient = sync.OnceValues(func() (NomadApiClient, error) {
	conn, err := bedrock.NewGrpcConn()
	if err != nil {
		return nil, err
	}
	return NewNomadApiClient(conn), nil
})

// Deploy deploys a job from a Nix definition
func Deploy(ctx context.Context, in *Job, opts ...grpc.CallOption) (*DeployResponse, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.Deploy(ctx, in, opts...)
}

func ListJobDefinitions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.ListJobDefinitions(ctx, in, opts...)
}

func ReadJobDefinition(ctx context.Context, in *ReadJobDefinitionRequest, opts ...grpc.CallOption) (*ReadJobDefinitionResponse, error) {
	client, err := loadClient()
	if err != nil {
		return nil, err
	}
	return client.ReadJobDefinition(ctx, in, opts...)
}
